sudo: false
language: python
python:
- 2.7
- 3.5
install:
- pip install tox
- pip install https://github.com/pypa/setuptools/releases/download/v28.2.0b1/setuptools-28.2.0b1-py2.py3-none-any.whl
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  # supply password with `travis encrypt --add deploy.password`
  distributions: dists
